### ISSUE TITLE
Team feedback on code review of June 17th, 2020 # Team 125 Elmos

### ISSUE THREAD

**Issue by descholar-ceo** [rahalrazika/apple-old-webpage#2]
## Corners of improvement
- [ ] Class naming: we should have used descriptive names in class naming
- [ ] The first text on the homepage is showing weird points, we should work on that
- [ ] We should try to use the percentage on gradients to make the navbar looks like the original one
- [ ] We should have tried to look for the original font family or the closest
- [x] In our codes there are a lot of extra-spacing, we should work on that
- [ ] We should try to download the images to use them locally because currently, we are using the URL, so since the URLs are pointing to the archive, they may change

**Comment by mohammadumar28** [comment]
Good Job! 👍 😄
